### ISSUE TITLE
Unable to use GoogleOAuthProvider in class based component

### ISSUE THREAD

**Issue by praveenkhoibamkh** [MomenSherif/react-oauth#234]
Cannot read properties of null (reading 'useState')
```
TypeError: Cannot read properties of null (reading 'useState')
    at useState (http://localhost:3000/static/js/bundle.js:30848:25)
    at useLoadGsiScript (http://localhost:3000/static/js/bundle.js:575:114)
    at GoogleOAuthProvider (http://localhost:3000/static/js/bundle.js:612:36)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:56615:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:59901:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:61197:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:46207:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:46251:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:46308:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:66182:11)
```

`  render() {
    return (
      <GoogleOAuthProvider clientId="198359311887-nbples0ve64fj6g0toe5nq1fn6gduatf.apps.googleusercontent.com">
          <GoogleLogin
            onSuccess={credentialResponse => {
              console.log(credentialResponse);
            }}
            onError={() => {
              console.log('Login Failed');
            }}
          />
       </GoogleOAuthProvider>
    )
  }`

    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "^5.0.1",

**Comment by veselinn** [comment]
@praveenkhoibamkh How did you fix your problem? I have the same error when using in a next.js app.

```
"react": "18.2.0",
"react-dom": "18.2.0",
```
