### ISSUE TITLE
How to solve Error: Google OAuth components must be used within GoogleOAuthProvider

### ISSUE THREAD

**Issue by marktophawk** [MomenSherif/react-oauth#99]
Hello~
Because I need to style my google loogin button ,so choose hook to implement.
However while npm build it, the error code appeared:

`Error: Google OAuth components must be used within GoogleOAuthProvider
    at useGoogleOAuth (C:\Users\project\Downloads\react\wego\node_modules\@react-oauth\google\dist\index.js:56:15)
    at useGoogleLogin (C:\Users\project\Downloads\react\wego\node_modules\@react-oauth\google\dist\index.js:127:52)
    at MyButton (C:\Users\project\Downloads\react\wego\.next\server\pages\[locale]\admin\login.js:488:92)
    at d (C:\Users\project\Downloads\react\wego\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\Users\project\Downloads\react\wego\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\Users\project\Downloads\react\wego\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\Users\project\Downloads\react\wego\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (C:\Users\project\Downloads\react\wego\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\Users\project\Downloads\react\wego\node_modules\next\dist\next-server\server\render.js:54:851)
    at Object.ctx.renderPage (C:\Users\project\Downloads\react\wego\.next\server\pages\_document.js:211:26)`

I am confused and have no idea how to let the hook (useGoogleLogin) to be surround with tag(GoogleOAuthProvider) .
Can you give me any hint or sample code?
Thank you very much~

My code is below:
`const MyButton = (props)=>{
	const login = useGoogleLogin({
		onSuccess: codeResponse => console.log(codeResponse),
		flow: 'auth-code',
    });
	return(
			<GoogleOAuthProvider clientId="here is myclientid">
			<Button
			type="button"
                fullWidth
                variant="contained"
			>Login With Google</Button>
		</GoogleOAuthProvider>
	)
}`

**Comment by taylor-tugboat** [comment]
The `<GoogleOAuthProvider` needs to be in a component in a parent above `MyButton`, it cant all be in the same component.

**Comment by marktophawk** [comment]
Thank you ~Taylor

**Comment by marktophawk** [comment]
Thank you~Taylor
